### PR TITLE
[ashell] All ashell commands check if the file exists

### LINKED ISSUE #799: ashell creates empty files when you make a typo
If you type the wrong file name in a run, parse, or du command at the ashell command line, it will create an empty file. I think this is because the underlying Zephyr FS API creates on open. So instead we should be checking for existence first and giving an error if it doesn't exist.

The 'cat' command *does* check, however its File not found error is missing a newline so it doesn't print nicely, so that could be fixed too.

### PR DESCRIPTION
**Pull request by brianjjones**
Also added newline to all the error strings to keep the terminal
output clean.

Fixes #799
Signed-off-by: Brian J Jones <brian.j.jones@intel.com>

### CODE REVIEW

File: src/ashell/shell-state.c [hunk 1]
```diff
@@ -39,17 +39,17 @@ static struct shell_state_config shell = {
     .state_flags = kShellTransferRaw
 };
 
-const char ERROR_NOT_RECOGNIZED[] = "Unknown command";
-const char ERROR_NOT_ENOUGH_ARGUMENTS[] = "Not enough arguments";
-const char ERROR_FILE_NOT_FOUND[] = "File not found";
-const char ERROR_EXCEDEED_SIZE[] = "String too long";
+const char ERROR_NOT_RECOGNIZED[] = "Unknown command\n";
```
Comment (jimmy-huang) [inline src/ashell/shell-state.c]: you should add the \n to the printf, not in the string here

**Comment by grgustaf** [comment]
Don't put the bug number in the summary line. Put "Fixes #799." in its own paragraph, just before your Signed-off-by.

**Comment by brianjjones** [comment]
@grgustaf updated

File: src/ashell/shell-state.c [hunk 2]
```diff
@@ -88,13 +88,26 @@ int32_t ashell_get_filename_buffer(const char *buf, char *destination)
...
         *destination = '\0';
-        comms_printf(ERROR_NOT_ENOUGH_ARGUMENTS);
+        comms_println(ERROR_NOT_ENOUGH_ARGUMENTS);
         return RET_ERROR;
     }
 
     return arg_len;
 }
 
+static int8_t file_exists(const char *buf, char *filename)
```
Comment (grgustaf) [inline src/ashell/shell-state.c]: This function name isn't great because it also gets the filename. That got me looking into it more.

I think a better way to fix this is to change fs_open_alloc() in file_utils.c. It takes a `mode` argument but mostly ignores it. If it starts with 'r' it should not be creating a new file. That would solve the problem I think.

Comment (brianjjones) [inline src/ashell/shell-state.c]: I foolishly saw fs_open_alloc and assumed it was a zephyr call.  Yeah makes more sense I'll take care of it there.

**Comment by grgustaf** [comment]
+1
