### PR TITLE
[k64f] Restore GPIO functionality by enabling pins via pinmux

### LINKED ISSUE #514: D0 and D1 cannot be used as output pins on FRDM_K64F
Flashing [test-k64f-pins.js](https://github.com/01org/zephyr.js/blob/master/tests/test-k64f-pins.js) on FRDM_K64F with commit a162db1, D0 and D1 cannot be used as output pins.

Output result:
```
Test K64f_pins APIs
PASS - K64f_pins: D0 defined
PASS - K64f_pins: D0 input
FAIL - K64f_pins: D0 output
PASS - K64f_pins: D1 defined
PASS - K64f_pins: D1 input
FAIL - K64f_pins: D1 output
```
Branch | Build ID | Date | Result
---|---|---|---
master | 5844f9f | Dec 7, 2016 | PASS
master | a162db1  | Dec 7, 2016 | FAIL

### PR DESCRIPTION
**Pull request by grgustaf**
Zephyr defaults changed around January for this board to no longer
set GPIO as default pinmux state for any of the external pins. So we
need to override them ourselves. Eventually we may need to get fancier
to set pinmux based on what the user's script wants to use the pins
for, or set up a default "ABI" for pinmux settings for the board. The
pinmux must be set up at board initialization time apparently.

Add new zjs_pinmux.c (currently for k64f only) to configure the
pinmux settings at initialization time.

Add a new prj.conf to enable GPIO port "D".

Add new samples GPIOInputs-k64.js and GPIOOutputs-k64.js to quickly
demonstrate which pins are functional.

With this update, pins D14 and D15 work as outputs for the first time.
But pin D8 on my rev E3 board doesn't seem to work as either anymore.

Fixes #514 and lets us finally see that #665 really was resolved.

Signed-off-by: Geoff Gustafson <geoff@linux.intel.com>

### CODE REVIEW

File: samples/tests/GPIOInputs-k64f.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+}, tick);
+
+// test all pins but D0
+var testpins = [pins.D1, pins.D2, pins.D3, pins.D4, pins.D5, pins.D6, pins.D7,
+                pins.D8, pins.D9, pins.D10, pins.D11, pins.D12, pins.D13,
+                pins.D14, pins.D15];
+var pincount = testpins.length;
+
+var count = 1;
+var gpios = []
```
Comment (jimmy-huang) [inline samples/tests/GPIOInputs-k64f.js]: missing ;

File: samples/tests/GPIOOutputs-k64f.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
+// Copyright (c) 2017, Intel Corporation.
+
+// Test code for FRDM-K64F that toggles each of pins D1-D15 as outputs
+// indefinitely. Configures D0 as an input and prints a message whenever it
+// changes, so you connect a jumper wire from D0 to each of the other pins (one
+// at a time) and see which ones generate a console message.
+
+console.log("Test external GPIOs as outputs...");
+
+console.log("\nWire D0 to each of D1-D15 in turn!");
```
Comment (jimmy-huang) [inline samples/tests/GPIOOutputs-k64f.js]: can't you put the \n in the end of the print above?

File: samples/tests/GPIOOutputs-k64f.js [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+    console.log("Output event", count);
+    count++;
+}
+
+// test all pins but D0
+var testpins = [pins.D1, pins.D2, pins.D3, pins.D4, pins.D5, pins.D6, pins.D7,
+                pins.D8, pins.D9, pins.D10, pins.D11, pins.D12, pins.D13,
+                pins.D14, pins.D15];
+var pincount = testpins.length;
+var gpios = []
```
Comment (jimmy-huang) [inline samples/tests/GPIOOutputs-k64f.js]: missing ;

File: samples/tests/GPIOOutputs-k64f.js (hunk 2 above)
Comment (grgustaf) [inline samples/tests/GPIOOutputs-k64f.js]: Yeah, but I think this is better - this is an 'extra' newline for a blank line; console.log already puts a newline. If I put it at the end it would look more like a normal newline.

**Comment by jimmy-huang** [comment]
+1
