### PR TITLE
[ocf] Move ocf.start() to correct location in client samples

### LINKED ISSUE #1115: [ocf] Can not find resource on OCF client
### Description

OCFClient can not find resource, it will be hanging.
 

### Test Code

Add console.log on [/samples/OcfClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClient.js):
    Add `console.log("----1----");` on line 44;
    Add `console.log("----2----");` on line 50;

Like this:
```
console.log("----1----");
client.findResources({ resourceType:"core.light" }, onfound).then(function(resource) {
    console.log("findResources() was successful, deviceId=" + resource.deviceId);
}).catch(function(error) {
    console.log("findResources() returned an error: " + error.name);
});
console.log("----2----");
```

Result:
selection_001

 

### Steps to Reproduction

Run test case and check console logs.
 

### Actual Result

Can not find resource and will be hanging.
 

### Expected Result

Find resource and work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 3950beb | Arduino 101 | May 9, 2017 | Fail

### PR DESCRIPTION
**Pull request by jprestwo**
Fixes #1115

Signed-off-by: James Prestwood <james.prestwood@intel.com>

### CODE REVIEW

File: samples/OcfNotifyClient.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
+// Copyright (c) 2016-2017, Intel Corporation.
```
Comment (grgustaf) [inline samples/OcfNotifyClient.js]: Why adding a new file? Was this left out before?

**Comment by grgustaf** [comment]
+1
