### PR TITLE
[ws] Fix K64F websocket build break

### LINKED ISSUE #1098: [ws] Fail to build WebSocket samples
### Description

Fail to build WebSocket samples
 
### Test Code

[WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js); [NodeWebSocketClient.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/NodeWebSocketClient.js)
 
### Steps to Reproduction

1. `make JS=samples/websockets/WebSocketServer.js`
2. `make BOARD=frdm_k64f JS=samples/websockets/WebSocketServer.js`
3.  `make BOARD=qemu_x86 qemu JS=samples/websockets/WebSocketServer.js`

### Actual Result

Fail to build WebSocket samples
selection_061
 

### Expected Result

Build WebSocket samples successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 78bc531 | Arduino 101 | May 3, 2017 | Fail
master | 78bc531 | FRDM-K64F | May 3, 2017 | Fail
master | 78bc531 | QEMU | May 3, 2017 | Fail

### PR DESCRIPTION
**Pull request by jprestwo**
Fixes #1098

Signed-off-by: James Prestwood <james.prestwood@intel.com>

### CODE REVIEW

File: src/zjs_web_sockets.c [hunk 1]
```diff
@@ -169,7 +169,7 @@ static void generate_key(char *key, uint32_t len, char *output, uint32_t olen)
     mbedtls_sha1(concat, strnlen(concat, 64), sha_out);
     uint32_t out_len;
     // base64 encode the sha1 hash
-    mbedtls_base64_encode(output, olen, &out_len, sha_out, 20);
+    mbedtls_base64_encode(output, olen, (size_t *)&out_len, sha_out, 20);
```
Comment (grgustaf) [inline src/zjs_web_sockets.c]: Cleaner to just declare out_len as size_t.

**Comment by grgustaf** [comment]
+1
