### PR TITLE
[ble] Fixed ble in Ashell

### LINKED ISSUE #1502: [ashell] Redundant message outputs
## Issue description
Redundant message is printed on terminal and it affect the next input.

## Test Code
[ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)

## Steps to reproduce
1. `make ROM=256 ashell; make dfu`
2. Flash ashell into 101 board, reset it and open port:
    `$ screen /dev/ttyACM0 115200`

## Actual Result
Redundant message is printed.
selection_001

## Expected Result
No redundant message outputs.

## Test Build
Branch| Commit id | Target Device |Test Date | Result 
---| ---| ---| ---|--- 
master | [6c160b5](https://github.com/01org/zephyr.js/commit/6c160b5d77c32b89e0fd165a644b4cd243d01929) | Arduino 101 | Aug 28, 2017 | Fail

### PR DESCRIPTION
**Pull request by jimmy-huang**
This fixes the issue where bluetooth doesn't work in Ashell,
since when running in Ashell, bt_enable() cannot be called until
the Bluetooth module is initialized.  This also fixes the error message
showing up when IDE is launched.

Fixes #1502

Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

File: src/zjs_ble.c [hunk 1]
```diff
@@ -1283,6 +1284,15 @@ static ZJS_DECL_FUNC(zjs_ble_descriptor)
...
 }
 
+#ifdef ZJS_ASHELL
+// INTERRUPT SAFE FUNCTION: No JerryScript VM, allocs, or release prints!
+static void ble_bt_ready(int err)
+{
+    DBG_PRINT("bt_ready() is called [err %d]\n", err);
+    zjs_ble_emit_powered_event();
+}
+#endif
```
Comment (grgustaf) [inline src/zjs_ble.c]: I don't like having two copies of this function.

It looks like to do this right, we need to have a "late init" hook, where the bt_enable would be called. We also maybe need to split BLE into a "service" layer and the "API" layer. So the service layer can be there even if the API layer isn't, and the service layer is what takes care of calling bt_enable. One goal would be to remove BUILD_MODULE_BLE from main.c (and anywhere else); all BT code should be in the zjs_bluetooth.c (service) and zjs_ble.c (API) or something.

If you don't want to tackle that now, let's at least remove this function from main.c and put it in ble.h to reuse the same function from main.c.

Comment (grgustaf) [reply src/zjs_ble.c]: Yeah, that's what I really meant by that hook - something that gets called after jerry_run() I think.

**Comment by jimmy-huang** [comment]
@grgustaf, updated patch

**Comment by grgustaf** [comment]
+1
