### PR TITLE
[test_promise] Enable test_promise module on A101

### LINKED ISSUE #796: [promise] Import test_promise module failed
### Description

Import test_promise module failed on Arduino 101 and FRDM-K64F. Not reproduced on Linux.
### Test Code

[test-promise.js](https://github.com/01org/zephyr.js/blob/master/tests/test-promise.js); [test-promise-stress.js](https://github.com/01org/zephyr.js/blob/master/tests/stress/test-promise-stress.js)
 
### Steps to Reproduction

1. `$ make JS=tests/test-promise.js`
2. `$ make dfu`
3. Reset device.
 
### Actual Result

test-promises

 ### Expected Result

Test case should be executed successfully. No error thrown. 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | b29dbbc | Arduino 101 | Mar 7, 2017 | Fail
master | b29dbbc | FRDM-K64F | Mar 7, 2017 | Fail
master | b29dbbc | Linux | Mar 7, 2017 | Pass

### PR DESCRIPTION
**Pull request by jprestwo**
Fixes #796

Signed-off-by: James Prestwood <james.prestwood@intel.com>

### CODE REVIEW

File: src/zjs_test_promise.c [hunk 1]
```diff
@@ -33,7 +33,7 @@ static jerry_value_t create_promise(const jerry_value_t function_obj,
     handle->value = TEST_VAL;
 
     jerry_value_t promise = jerry_create_object();
-    ZJS_PRINT("Testing promise, object = %u\n", promise);
+    ZJS_PRINT("Testing promise, object = %lu\n", promise);
```
Comment (grgustaf) [inline src/zjs_test_promise.c]: Can you leave it %u and just cast (unsigned int)promise for now?

File: src/zjs_test_promise.c [hunk 2]
```diff
@@ -33,7 +33,7 @@ static jerry_value_t create_promise(const jerry_value_t function_obj,
     handle->value = TEST_VAL;
 
     jerry_value_t promise = jerry_create_object();
-    ZJS_PRINT("Testing promise, object = %lu\n", promise);
+    ZJS_PRINT("Testing promise, object = %u\n", (unsigned long)promise);
```
Comment (grgustaf) [inline src/zjs_test_promise.c]: (unsigned int) not long

**Comment by grgustaf** [comment]
+1
