### PR TITLE
[build] Fixed linux build error on MacOS

### LINKED ISSUE #1349: [mac] make linux target broke on Mac after zephyr updated to 1.8
### Description

This issue blocks most test on MacOS. Building linux target on Mac failed after zephyr updated to 1.8. 

### Steps to Reproduction

1. `make BOARD=linux`

### Actual Result

1. Building linux target failed on Mac.
screen shot 2017-07-10 at 4 20 33 pm

 ### Expected Result

Building successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 05fda87 | linux | Jul 11, 2017 | Fail

### PR DESCRIPTION
**Pull request by jimmy-huang**
Fixes #1349

Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -1,9 +1,9 @@
 // Copyright (c) 2016-2017, Intel Corporation.
 
-#ifndef ZJS_LINUX_BUILD
 // C inclues
```
Comment (grgustaf) [inline src/main.c]: fix typo while you're here :)

**Comment by jimmy-huang** [comment]
@grgustaf fixed

**Comment by grgustaf** [comment]
+1
