### PR TITLE
[spi] Remove test point for test-spi.js

### LINKED ISSUE #1445: [spi] Read and write 8 bits data failed if set 16 bits for SPI
### Description

When running [test-spi.js](https://github.com/01org/zephyr.js/blob/master/tests/test-spi.js), read and write 8 bits data failed if set 16 bits for SPI.
 
### Test Code

[test-spi.js](https://github.com/01org/zephyr.js/blob/master/tests/test-spi.js);
 
### Steps to Reproduction

 1. `make JS=tests/test-spi.js`
 2. `make dfu`
### Actual Result

 selection_148

### Expected Result

 No error 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | ca7af311 | Arduino 101 | Aug 9 2017 | Fail
master | ca7af311 | FRDM-K64F | Aug 9 2017 | Fail

### PR DESCRIPTION
**Pull request by cuiyanx**
Fixes #1445 

Signed-off-by: Cui Yan <yanx.cui@intel.com>

### CODE REVIEW

File: tests/test-spi.js [hunk 1]
```diff
@@ -70,10 +70,14 @@ for (var i = 0; i < spiBusBits.length; i++) {
     spiBus = spi.open(init);
 
     for (var j = 0; j < dataNumber.length; j++) {
-        var bufferNumber = spiBus.transceive(deviceNum, dataNumber[j]);
-        assert(bufferNumber.toString("hex") === checkNumber[i][j],
-               "SPIBusTransceive: read and write number array by bits '" +
-               spiBusBits[i] + "'");
+        if (spiBusBits[i] === 16 && j === 1) {
```
Comment (jimmy-huang) [inline tests/test-spi.js]: Can you add comments here like why we are removing this specific test case for 16bit mode?  lgtm otherwise.

Comment (brianjjones) [reply tests/test-spi.js]: If I understand correctly it is in reference to issue #1445, its removing the invalid test case.

**Comment by brianjjones** [comment]
LGTM +1
