### PR TITLE
[modules] Fix to allow linux to load JS modules

### LINKED ISSUE #1687: [linux] Assert doesn't work on Linux
### Description

This issue a regression issue. Most of tests in zephyr.js will get TypeError on Linux.
 
### Test Code

[test-buffer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer.js);
[test-buffer-rw.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer-rw.js);
[test-callbacks.js](https://github.com/01org/zephyr.js/blob/master/tests/test-callbacks.js);
[test-timers.js](https://github.com/01org/zephyr.js/blob/master/tests/test-timers.js);
[test-error.js](https://github.com/01org/zephyr.js/blob/master/tests/test-error.js);
[test-eval.js](https://github.com/01org/zephyr.js/blob/master/tests/test-eval.js);
[test-event.js](https://github.com/01org/zephyr.js/blob/master/tests/test-event.js);
[test-gpio.js](https://github.com/01org/zephyr.js/blob/master/tests/test-gpio.js);
[test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js);
[test-ocfclient.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfclient.js);
[test-board.js](https://github.com/01org/zephyr.js/blob/master/tests/test-board.js);

### Steps to Reproduction

1. `make BOARD=linux`
2. `./outdir/linux/release/jslinux tests/test-buffer.js`
 
or simply code:
```
var assert = require('Assert.js');
assert(true, "assert works fine");
```
### Actual Result

selection_008

 ### Expected Result

selection_010

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | cbec79d | Arduino 101 | Dec 4, 2017 | Pass
master | 091f6ce - cbec79d | Linux | Dec 4, 2017 | Fail
master | 091f6ce - cbec79d | MacOS | Dec 4, 2017 | Fail
master | 62697b3 | Linux | Dec 4, 2017 | Pass
master | 62697b3 | MacOS | Dec 4, 2017 | Pass

### PR DESCRIPTION
**Pull request by brianjjones**
Linux requires the module object be returned to work.
Fixes #1687

Signed-off-by: Brian J Jones <brian.j.jones@intel.com>

### CODE REVIEW

File: src/zjs_modules.c [hunk 1]
```diff
@@ -189,13 +187,18 @@ static ZJS_DECL_FUNC(native_require_handler)
...
+    }
+
     char module[module_size];
     zjs_copy_jstring(argv[0], module, &module_size);
 
     // Try each of the resolvers to see if we can find the requested module
     jerry_value_t result = jerryx_module_resolve(argv[0], resolvers, 3);
     if (jerry_value_has_error_flag(result)) {
-        ERR_PRINT("Couldn't load module %s\n", module);
+        //ERR_PRINT("Couldn't load module %s\n", module);
```
Comment (grgustaf) [inline src/zjs_modules.c]: How about make this a DBG_PRINT, module name would still be useful for debugging.

**Comment by grgustaf** [comment]
+1
