### PR TITLE
[callback] Fixed crash when removing callback with id -1

### LINKED ISSUE #1593: [gpio] Segmentation fault in test-gpio on Linux
### Description

This is a regression issue. When running test-gpio.js on Linux,  `Segmentation fault (core dumped)` occurs.
### Test Code

[test-gpio.js](https://github.com/01org/zephyr.js/blob/master/tests/test-gpio.js)
 
### Steps to Reproduction

1. `make BOARD=linux `
2. `./outdir/linux/release/jslinux tests/test-gpio.js`
### Actual Result

 selection_034

### Expected Result

 
selection_036

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 0a17d94 | Linux | Oct 16, 2017 | Pass
master | cd3f44e - 1d5a99d | Linux | Oct 16, 2017 | Fail

### PR DESCRIPTION
**Pull request by jimmy-huang**
There's no check on callback id when calling zjs_remove_callback(),
this will cause a segfault when callback id has not been set or
has a negative value.

Fixes #1593

Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

**Comment by jimmy-huang** [comment]
@grgustaf all right, updated patch

File: src/zjs_callbacks.c [hunk 1]
```diff
@@ -327,18 +327,13 @@ static void zjs_remove_callback_priv(zjs_callback_id id, bool skip_flush)
...
-    // Don't free a callback after its been freed
-    if (GET_CB_REMOVED(cb_map[id]->flags)) {
-        return;
-    }
-
     CB_LOCK();
     if (id >= 0 && cb_map[id]) {
+        // Don't free a callback after its been freed
+        if (GET_CB_REMOVED(cb_map[id]->flags)) {
+            return;
```
Comment (grgustaf) [inline src/zjs_callbacks.c]: I think you need to call CB_UNLOCK here or you will break things...

**Comment by grgustaf** [comment]
+1

**Comment by brianjjones** [comment]
+1
