### PR TITLE
 [timers] Revert patch #1542 for linux timers

### LINKED ISSUE #1579: [Mac] Fail to build Linux and Qemu target on Mac
### Description

This is an regression issue and it is blocked weekly test on MacOS. Building linux and qemu target on Mac failed. 

### Test Code

All samples and tests

### Steps to Reproduction

1. Building linux on MAC by command: `make BOARD=linux`
2. Building qemu on MAC by follow instructions: [building-qemu-and-arduino-101-targets](https://github.com/01org/zephyr.js#building-qemu-and-arduino-101-targets)

### Actual Result

1. Building linux target failed on Mac.
screen shot 2017-10-11 at 2 34 10 pm

2. Building qemu target failed on Mac.
screen shot 2017-10-11 at 2 33 58 pm

 ### Expected Result

Building successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a36b2c9 - cd3f44e | qemu & linux | Oct 11, 2017 | Fail
master | 4b77505 | qemu & linux | Oct 11, 2017 | Pass

### Additional Information

This issue is caused by commit a36b2c9.

### PR DESCRIPTION
**Pull request by jimmy-huang**
The new timer patch #1542 uses librt which doesn't build on MacOS,
this patch revert linux builds to previous old timer
implementation for compatibility and adds a FIXME for all the places
the patch was reverted.  We need to find a way to add a cross-platform
implementation for timers that will work on both Linux and MacOS.

Fixes #1579

### CODE REVIEW

**Comment by jimmy-huang** [comment]
@jprestwo can you review this?

File: src/zjs_common.c [hunk 1]
```diff
@@ -27,23 +27,49 @@ char *zjs_shorten_filepath(char *filepath)
...
 
+static u8_t init = 0;
+static int seconds = 0;
+#else
 static int start = 0;
+#endif
 
 int zjs_get_sec(void)
 {
+#ifdef ZJS_LINUX_BUILD
```
Comment (jprestwo) [inline src/zjs_common.c]: I think this could be left without the ifdef. The Linux port should have `zjs_port_timer_get_uptime()` and if it doesn't then you could just move this ifdef'ed code into that function. That would at least simplify this piece.

File: src/zjs_common.c [hunk 2]
```diff
@@ -27,23 +27,49 @@ char *zjs_shorten_filepath(char *filepath)
...
         start = zjs_port_timer_get_uptime() / 1000;
     }
     return (zjs_port_timer_get_uptime() / 1000) - start;
+#endif
 }
 
 int zjs_get_ms(void)
 {
+#ifdef ZJS_LINUX_BUILD
+    struct timespec now;
```
Comment (jprestwo) [inline src/zjs_common.c]: Same comment as above

**Comment by jprestwo** [comment]
LGTM

**Comment by grgustaf** [comment]
+1
